name: CustomEntitiesAPI
main: me.dablakbandit.customentitiesapi.CustomEntitiesAPI
author: Dablakbandit
version: 1.4
commands:
  customentitiesapi:
    permission: customentitiesapi.test
    alias: ces