name: CustomEntitiesAPI
main: me.dablakbandit.customentitiesapi.CustomEntitiesAPI
author: Dablakbandit
version: 1.6
commands:
  customentitiesapi:
    permission: customentitiesapi.test
    aliases: ces